# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: images/favicon.ico

# Personal info
name: Juan Enrique Rubio
title: ICS Cybersecurity Consultant
email: info@jercobyte.com
#phone:
#website: www.nics.uma.es/rubio

darkmode: never

# Social links
twitter_username: jercobyte
github_username:  jercobyte
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
instagram_username: jercobyte
linkedin_username: jercobyte
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
#orcid_username: 0000-0002-7338-9390
google_scholar_username: 8ah_zWoAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0" (este)

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi there! My name is Juan Enrique, and I am a Ph.D. candidate at the University of Malaga currently working as ICS cybersecurity consultant at VASS. I obtained a Bachelor's degree in Computer Science in 2014 and my Master's Degree in Computer Science in 2016, both with distinction from the same University. I also collaborated in the Department of Computer Science from 2013 to 2021, focusing my research activities on the protection of critical infrastructures in the context of national and international projects. Ever since, my work revolves around the analysis of cybersecurity threats that arise with the paradigm of Industry 4.0 and the concept of Industrial Internet of Things, interconnecting productive processes of all sectors with cutting-edge information and communications technologies.
#  Mr. Juan Enrique is a PhD student at the University of Malaga, who receives funds from the Spanish Ministry of Education under the FPU program. He obtained the Bachelor's degree in Computer Science in 2014 and the Master's Degree in Computer Science in 2016, both with distinction by the same University. He has been a collaborator in the Department of Computer Science since 2013, and his research activities today are focused on the protection of critical infrastructures. In particular, among its publications, we can highlight the analysis of cybersecurity threats that arise with the paradigm of Industry 4.0 and the concept of Industrial Internet of Things, interconnecting productive processes of all sectors with cutting-edge information and communications technologies. In this sense, Juan Enrique also has works in the design of mechanisms that preserve the privacy of users in the context of Smart Grid, and currently works in national and international projects related to these areas.


# Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

# You can even add paragraphs by using empty lines like this and add anything else markdown supports such as
#   - Lists
#   - Tables
#   - <a href="google.com">Links</a>
#   - Images

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  Woo hoo! Still here? I didn't think you were going to scroll that long. That only means either you want to know more or you are trying to reach me for any other matter. 

  As for the former, I can just say that I am a hell of a freak, kind of amateur photographer and that I would spend years on a problem until I got it solved. Pigheaded as a mule but shy as a fox, I deeply enjoy spending time with my closest people. I turn out to be very organized and tidy for serious stuff, but not that much for the rest of my mind. Oh, and I love New York.

  As for the latter, please, do not hesitate to contact me at [info@jercobyte.com](mailto:info@jercobyte.com) or any other network linked in the header. We are in touch!

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
